---
- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: "{{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: docker_service_manage | bool

- name: Add key
  ansible.builtin.apt_key:
    data: "{{ result.content }}"
    state: present
